### ISSUE TITLE
How to do js validation?

### ISSUE THREAD

**Issue by mntdamania** [tslocke/hobocookbook#4]
I'm having hard time following hobo. I've already written js function for validation. I want this function to be called onsubmit and stop the form submit if data is invalid.. How do I accomplish this with hobo? This is what I've done so far. 

``` html
<div param="actions">
  <submit label="#{ht 'property.actions.save', :default=>['Save'], :onsubmit => 'callme()'}" param/><or-cancel param="cancel"/></div>
```

But the above code is not even appearing on html source of the browser. Even the simplest things in rails takes hours to do in hobo :(

**Comment by mntdamania** [comment]
This is how the form looks like

``` html
<form action="/admin/properties/539-bed-bath-12323" class="property" enctype="multipart/form-data" method="post">
```

 and this is the js validation code using prototype

``` javascript
$$('.property').onsubmit = function(){
  exp_date = $("property_expiration_date").value;
  date_sold = $("property_date_sold").value;
  alert("onsubmit called");
  if (exp_date.length > 0)
  { 
    date_obj = new Date(exp_date).to_s;
    if (date_obj == "Invalid Date")
    {
      alert("Please enter valid expiry date.");
      return false;
    }
  }
  if (date_sold.length > 0)
  { 
    date_obj = new Date(date_sold).to_s;
    if (date_obj == "Invalid Date")
    {
      alert("Please enter valid expiry date.");
      return false;
    }
  }
  alert("form returned true");
  return true;
}
```

I'm trying to validate the entered date.. Please advise me how to move forward or a working way to validate dates in model.

Thanks

**Comment by bryanlarsen** [comment]
You've got your onsubmit as an option to an i18n translation function inside of a label.

try this:

```
<submit label="Save" onsubmit="callme()" />
```

You're probably not using i18n or parametrization, so just leave those out until you need them and you understand them.

Also, the right place for questions like this is the hobo users mailing list.
