### ISSUE TITLE
Would you please see if you have a copy of your old article? 

### ISSUE THREAD

**Issue by sserdyuk** [tslocke/hobocookbook#6]
@tslocke I have to maintain an old Hobo app, and I scrambling every bid of information that's available on the technology. I have set up a copy of the Cookbook, but some pieces aren't in the git repo. Particularly, there's a link to a missing article that explains `part` and `update` elements of AJAX. I am wondering if by any chance you still have it sitting on your hard drive. The link to the article was `http://cookbook.hobocentral.net/recipes/8-use-parts-on-repeated-elements`.

**Comment by tslocke** [comment]
Hi - Sorry, can’t find it. Have you tried the wayback machine?

**Comment by sserdyuk** [comment]
@tslocke You're a genius. Thank you.
